### ISSUE TITLE
Conventions

### ISSUE THREAD

**Issue by fowardslash** [ThatKawaiiSam/eGrounds#5]
Package names should be like this:
bar.foo
NOT
bar.Foo

**Comment by ThatKawaiiSam** [comment]
could you show me an example of  that within my code, im a still a little confused.

**Comment by fowardslash** [comment]
So for your case we will just take a random package:
com/theeximusmc/egrounds/Commands/
This should be
com/theeximusmc/egrounds/commands/
instead 

If you would like to learn more
[](https://www.javatpoint.com/java-naming-conventions)

You can also search google for "proper java conventions" and readup on some more documentation, but I feel that link should suffice as everything else seems good.

**Comment by ThatKawaiiSam** [comment]
Ok thank you didn't know there was any conventions when it came to packages. This will be fixed when I get the time, thanks!
