### ISSUE TITLE
[Dependancy] Use Lombok

### ISSUE THREAD

**Issue by fowardslash** [ThatKawaiiSam/eGrounds#6]
You should highly consider using lombok for getter and setters as it makes your code a lot cleaner! This is not required but it would help a lot.

P.S
Lombok is not only for getter and setters it has much more!
[https://projectlombok.org/](url)

**Comment by ThatKawaiiSam** [comment]
Hi fowardslash,

I've already started using lombok for the rewrite of this plugin, but thankyou for the suggestion anyways!
